Lab14/Controllers/Kind_sportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab14;

namespace Lab14.Controllers
{
    public class Kind_sportController : Controller
    {
        private DotNetEntities db = new DotNetEntities();

        // GET: Kind_sport
        public async Task<ActionResult> Index()
        {
            return View(await db.Kind_sport.ToListAsync());
        }

        // GET: Kind_sport/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kind_sport kind_sport = await db.Kind_sport.FindAsync(id);
            if (kind_sport == null)
            {
                return HttpNotFound();
            }
            return View(kind_sport);
        }

        // GET: Kind_sport/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kind_sport/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id_kind,Name_kind,Group_kind")] Kind_sport kind_sport)
        {
            if (ModelState.IsValid)
            {
                db.Kind_sport.Add(kind_sport);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(kind_sport);
        }

        // GET: Kind_sport/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kind_sport kind_sport = await db.Kind_sport.FindAsync(id);
            if (kind_sport == null)
            {
                return HttpNotFound();
            }
            return View(kind_sport);
        }

        // POST: Kind_sport/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id_kind,Name_kind,Group_kind")] Kind_sport kind_sport)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kind_sport).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(kind_sport);
        }

        // GET: Kind_sport/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kind_sport kind_sport = await db.Kind_sport.FindAsync(id);
            if (kind_sport == null)
            {
                return HttpNotFound();
            }
            return View(kind_sport);
        }

        // POST: Kind_sport/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Kind_sport kind_sport = await db.Kind_sport.FindAsync(id);
            db.Kind_sport.Remove(kind_sport);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lab14/Controllers/Sport_clubController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab14;

namespace Lab14.Controllers
{
    public class Sport_clubController : Controller
    {
        private DotNetEntities db = new DotNetEntities();

        // GET: Sport_club
        public async Task<ActionResult> Index()
        {
            var sport_club = db.Sport_club.Include(s => s.Kind_sport);
            return View(await sport_club.ToListAsync());
        }

        // GET: Sport_club/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sport_club sport_club = await db.Sport_club.FindAsync(id);
            if (sport_club == null)
            {
                return HttpNotFound();
            }
            return View(sport_club);
        }

        // GET: Sport_club/Create
        public ActionResult Create()
        {
            ViewBag.id_kind = new SelectList(db.Kind_sport, "id_kind", "Name_kind");
            return View();
        }

        // POST: Sport_club/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id_club,id_kind,Name_club,Text_club,CreateDate_club,Image_club")] Sport_club sport_club)
        {
            if (ModelState.IsValid)
            {
                db.Sport_club.Add(sport_club);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.id_kind = new SelectList(db.Kind_sport, "id_kind", "Name_kind", sport_club.id_kind);
            return View(sport_club);
        }

        // GET: Sport_club/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sport_club sport_club = await db.Sport_club.FindAsync(id);
            if (sport_club == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_kind = new SelectList(db.Kind_sport, "id_kind", "Name_kind", sport_club.id_kind);
            return View(sport_club);
        }

        // POST: Sport_club/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id_club,id_kind,Name_club,Text_club,CreateDate_club,Image_club")] Sport_club sport_club)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sport_club).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.id_kind = new SelectList(db.Kind_sport, "id_kind", "Name_kind", sport_club.id_kind);
            return View(sport_club);
        }

        // GET: Sport_club/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sport_club sport_club = await db.Sport_club.FindAsync(id);
            if (sport_club == null)
            {
                return HttpNotFound();
            }
            return View(sport_club);
        }

        // POST: Sport_club/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Sport_club sport_club = await db.Sport_club.FindAsync(id);
            db.Sport_club.Remove(sport_club);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lab14/Views/Kind_sport/Create.cshtml
@model Lab14.Kind_sport

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kind_sport</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name_kind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name_kind, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name_kind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Group_kind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Group_kind, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Group_kind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Lab14/Views/Kind_sport/Delete.cshtml
@model Lab14.Kind_sport

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kind_sport</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name_kind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_kind)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Group_kind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group_kind)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lab14/Views/Kind_sport/Details.cshtml
@model Lab14.Kind_sport

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Kind_sport</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name_kind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_kind)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Group_kind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group_kind)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_kind }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Lab14/Views/Kind_sport/Edit.cshtml
@model Lab14.Kind_sport

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kind_sport</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_kind)

        <div class="form-group">
            @Html.LabelFor(model => model.Name_kind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name_kind, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name_kind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Group_kind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Group_kind, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Group_kind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Lab14/Views/Kind_sport/Index.cshtml
@model IEnumerable<Lab14.Kind_sport>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    <br></br>
    @Html.ActionLink("Ссылка на Sport_club", "Index", "Sport_club", new { area = "" }, new { @class = "navbar-brand" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name_kind)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Group_kind)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name_kind)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Group_kind)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_kind }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_kind }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_kind })
        </td>
    </tr>
}

</table>

Lab14/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Lab14/Views/Sport_club/Create.cshtml
@model Lab14.Sport_club

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sport_club</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_kind, "id_kind", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_kind", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_kind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name_club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name_club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name_club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text_club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text_club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text_club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate_club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate_club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate_club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image_club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image_club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image_club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Lab14/Views/Sport_club/Delete.cshtml
@model Lab14.Sport_club

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sport_club</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name_club)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_club)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text_club)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text_club)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate_club)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate_club)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_club)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image_club)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kind_sport.Name_kind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kind_sport.Name_kind)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lab14/Views/Sport_club/Details.cshtml
@model Lab14.Sport_club

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Sport_club</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name_club)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name_club)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text_club)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text_club)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate_club)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate_club)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image_club)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image_club)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kind_sport.Name_kind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kind_sport.Name_kind)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_club }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Lab14/Views/Sport_club/Edit.cshtml
@model Lab14.Sport_club

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sport_club</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_club)

        <div class="form-group">
            @Html.LabelFor(model => model.id_kind, "id_kind", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_kind", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_kind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name_club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name_club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name_club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text_club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text_club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text_club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate_club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate_club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate_club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image_club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image_club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image_club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Lab14/Views/Sport_club/Index.cshtml
@model IEnumerable<Lab14.Sport_club>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    <br></br>
    @Html.ActionLink("Ссылка на Kind_sport", "Index", "Kind_sport", new { area = "" }, new { @class = "navbar-brand" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name_club)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text_club)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDate_club)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image_club)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kind_sport.Name_kind)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name_club)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text_club)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateDate_club)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Image_club)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kind_sport.Name_kind)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_club }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_club }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_club })
        </td>
    </tr>
}

</table>